init:
  - git config --global core.autocrlf true
branches:
  only:
    - master
    - dev
build:
  project: Entr.sln
  parallel: true
test:
  assemblies:
    only:
    - '**\*.Tests.dll'
clone_depth: 1
deploy: off
image: Visual Studio 2017