dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

image: Visual Studio 2017

branches:
  only:
  - master

init:
  # Best practice (Windows line endings different to Unix/Linux)
  - cmd: git config --global core.autocrlf true

before_build:
  # Display .NET Core version
  - cmd: dotnet --version

build_script:
  - cmd: dotnet build Entr.sln

deploy: off

test_script:
  - cmd: dotnet test Entr.sln
  
test:
  assemblies:
    only:
    - '**\*.Tests.dll'
