init:
  - git config --global core.autocrlf true
branches:
  only:
    - master
    - dev
build_script:
  - ps: .\build.ps1
test:
  assemblies:
    - '**\*.Tests.dll'
clone_depth: 1
test: on
deploy: off
image: Visual Studio 2017