init:
  - git config --global core.autocrlf true
branches:
  only:
    - master
    - dev
build_script:
  - ps: .\build.ps1
test_script:
  - ps: .\test.ps1
clone_depth: 1
test: on
deploy: off
image: Visual Studio 2017