version: "3.9"
services:
  sample_web:
    build:
      context: .
      dockerfile: ./samples/SampleApi/Dockerfile
    environment:
      ConnectionStrings__Default: "server=db;database=SampleApi;user=sa;password=${MSSQL_SA_PASSWORD}"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "${WEB_CERTIFICATE_PASSWORD}"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/aspnetapp.pfx"
      ASPNETCORE_URLS: "https://+:443"
      ASPNETCORE_Environment: "Development"
    ports:
      - "5001:443"
    volumes:
      - ${HOME}/.aspnet/https:/https/
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      ACCEPT_EULA: ${ACCEPT_EULA}
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - mssql:/var/opt/mssql
volumes:
  mssql:
    external: true
