version: "3.9"
services:
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "P@5Sw0rd123"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Developer"
        ports:
            - "1433:1433"
