//HintName: Entr.Domain.Generators.Tests.RoleId.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the EntrEntityId source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // publicly visible type or member must be documented

using System;
using System.ComponentModel;
using System.Globalization;
using System.Text.Json;
using System.Text.Json.Serialization;
using Entr.Domain;

namespace Entr.Domain.Generators.Tests;

[JsonConverter(typeof(RoleIdJsonConverter))]
[TypeConverter(typeof(RoleIdTypeConverter))]
readonly partial struct RoleId : IEquatable<RoleId>
{
    public RoleId(int value)
    {
        if (value == default)
        {
            throw new ArgumentException("Specified value cannot be default(int)", nameof(value));
        }

        Value = value;
    }

    public int Value { get; }

    public override int GetHashCode()
    {
        return HashCode.Combine(typeof(RoleId), Value);
    }

    public override string ToString() => Value.ToString();

    public override bool Equals(object obj)
        => obj is RoleId other && Equals(this, other);
    public bool Equals(RoleId other)
        => Equals(this, other);

    public static bool Equals(RoleId? left, RoleId? right)
    {
        if (!left.HasValue && !right.HasValue) return true;
        if (!left.HasValue || !right.HasValue) return false;

        return left.Value.Value == right.Value.Value;
    }

    public static bool operator ==(RoleId left, RoleId right) =>
        Equals(left, right);
    public static bool operator !=(RoleId left, RoleId right) =>
        !Equals(left, right);

    public sealed class RoleIdJsonConverter : JsonConverter<RoleId>
    {
        public override RoleId Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
           => new RoleId(reader.GetInt32()!);

        public override void Write(Utf8JsonWriter writer, RoleId id, JsonSerializerOptions options)
           => writer.WriteNumberValue(id.Value);
      }

    public sealed class RoleIdTypeConverter : TypeConverter
    {
        public override bool CanConvertFrom(ITypeDescriptorContext context, Type sourceType)
            => sourceType == typeof(int) || sourceType == typeof(string);
        public override bool CanConvertTo(ITypeDescriptorContext context, Type destinationType)
            => destinationType == typeof(int) || destinationType == typeof(string);

        public override object ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, object value)
        {
            if (value.GetType() == typeof(string))
            {
                return new RoleId(int.Parse((string)value));
            }

            return new RoleId((int)value);
        }

        public override object ConvertTo(ITypeDescriptorContext context, CultureInfo culture, object value, Type destinationType)
        {
            if (destinationType == typeof(string))
            {
                return ((RoleId)value).Value.ToString();
            }

            return ((RoleId)value).Value;
        }
    }
}
